### ISSUE TITLE
How to get a Quote for product before shipping?

### ISSUE THREAD

**Issue by uwejan** [rawilk/laravel-ups#2]
Using shipping 
https://randallwilk.dev/docs/laravel-ups/v2/apis/shipping
Am i able to get `quotes` before i request for shipping? or do i need to implement the `rate` class?
1 more question, the `shipper_number` is the same as `avvount number` in the UPS dashboared right?

**Comment by rawilk** [comment]
> Am i able to get quotes before i request for shipping? or do i need to implement the rate class?

I believe you need the rate class, but I'm not 100% on that. I haven't had a need to get rates before hand so I'm not exactly sure how it all works.

> 1 more question, the shipper_number is the same as avvount number in the UPS dashboared right?

I believe they are the same numbers, yes.
