### ISSUE TITLE
[Feature Request]: Moving to RESTful API instead of XML 

### ISSUE THREAD

**Issue by overrider** [rawilk/laravel-ups#28]
### Feature Description

We have Information from our customer support staff at UPS that UPS is in the middle of changing over to OAuth 2.0, and XML/SOAP API Formats will no longer be available starting June 3rd 2024. Instead this will be replace with RESTful Version. I know its a year out, but do you have plans/comments already for this?

**Comment by rawilk** [comment]
Hey, sorry I didn't see this earlier. To answer your question, I'm not 100% sure if I'm going to implement it or not. It all comes down to if I'll have time and interest in modifying the package, however I'd be open to PR's on this as well.
