### ISSUE TITLE
Tracking API not working in testmode

### ISSUE THREAD

**Issue by TuhiranDevbhuti** [rawilk/laravel-ups#5]
Hello @rawilk I went through integrating the shipping and Tracking API into my Laravel application. But the tracking API always returns  "No tracking information available"
Please Follow the first image in the response of Shipping API & the second one is of tracking API
![image](https://user-images.githubusercontent.com/48747782/161555620-55877050-7feb-4c7a-ad1a-4f86e7cd51d2.png)
![image](https://user-images.githubusercontent.com/48747782/161555661-30fd5012-5bde-4e93-85ba-557859c1de7d.png)

**Comment by TuhiranDevbhuti** [comment]
> Hello @rawilk I went through integrating the shipping and Tracking API into my Laravel application. But the tracking API always returns "No tracking information available" Please Follow the first image in the response of Shipping API & the second one is of tracking API ![image](https://user-images.githubusercontent.com/48747782/161555620-55877050-7feb-4c7a-ad1a-4f86e7cd51d2.png) ![image](https://user-images.githubusercontent.com/48747782/161555661-30fd5012-5bde-4e93-85ba-557859c1de7d.png)

Hello @rawilk please have look into the matter and me accordingly

**Comment by TuhiranDevbhuti** [comment]
Hello @rawilk Please have look into the issue I'm facing in the tracking API

**Comment by TuhiranDevbhuti** [comment]
Hello @rawilk Please have a look into the tracking API of the Laravel UPS of v1
![image](https://user-images.githubusercontent.com/48747782/162195720-7e69a6a4-a197-4123-85e2-d81d038f3d13.png)

**Comment by rawilk** [comment]
I'm not sure if you're new to open source or something, but nobody owes you their time to look into issues you're having on your projects. Asking every day for someone to look into something is certainly not going to make them want to help you any more.

As far as your issue goes, it's really not an issue with the package at all. If you read the UPS docs you would find that you need to use their test tracking numbers in a sandbox environment. 

I've conveniently provided a class in the package with constants for some of the test tracking numbers for UPS: https://github.com/rawilk/laravel-ups/blob/main/src/Apis/Tracking/TrackingTestNumbers.php

**Comment by TuhiranDevbhuti** [comment]
Thanks for @rawilk. Please don't mind. I'm new open source. From the next time I will keep that in mind. Thank you once again.
